### PR TITLE
Change init script name from S20urandom to S02urandom

### PR DESCRIPTION
**Pull request by mistepien**
This is a solution for poor randomness of RANDOM function is S03splash.

### CODE REVIEW

**Comment by tcamargo** [comment]
sorry? what do you mean by s03splash?

**Comment by mistepien** [comment]
script /etc/init.d/S03splash. you may have custom splash images and they are shown before running ES, scripts uses RANDOM function and the very beginning of booting system this function is quite predictable.

**Comment by tcamargo** [comment]
There is no random call in S03splash. I think you are thinking about Recalbox.

**Comment by mistepien** [comment]
In S03splash RANDOM bash function is used. Does not it use kernel mechanism?
I've tested that S02urandom trick and now the circulation of splash pictures is much better.

https://github.com/batocera-linux/batocera.linux/pull/1529/commits/8fde8ee9646af6171cfc58107910a5a57a872f05

**Comment by nadenislamarre** [comment]
i found it strange that it behaves better.
the s03 is just used to generate more quickly random values for ssh, but by default, the kernel takes values from random hardware events.
without that, it is always the same video playing ?

**Comment by tcamargo** [comment]
> There is no random call in S03splash. I think you are thinking about Recalbox.

Sorry, my mistake. Im not against the change. I only would like to avoid a new change to buildroot.

**Comment by mistepien** [comment]
I was testing other things and the randomness of splash screen lost it's priority. I think that we can delete that PR. This is so trivial that making this once again is very easy and quick.

**Pull request closed without merging**
