### PR TITLE
Bump FMT

### PR DESCRIPTION
**Pull request by liberodark**
Build OK

### CODE REVIEW

**Comment by nadenislamarre** [comment]
it is a prerequisite to something ?

**Comment by liberodark** [comment]
Yes I needed it because for a deps update.
But if it's not merge that's okay.
The update is done on my side.

**Comment by nadenislamarre** [comment]
this is a dep of what package ?

**Comment by liberodark** [comment]
I noticed a conflict with dolphin for this PR so I close it.

**Pull request closed without merging**
