### PR TITLE
Fix PW

### PR DESCRIPTION
**Pull request by liberodark**
Build OK

### CODE REVIEW

**Comment by dmanlfc** [comment]
have to check, i think sdl2 shouldn't have a dependency on pipewire...

**Comment by nadenislamarre** [comment]
yes, the dependancy is not wanted on our case.
as done in this pr.

**Comment by nadenislamarre** [comment]
PIPEWIRE_CONF_OPTS += --wrap-mode=default

why ?

**Comment by nadenislamarre** [comment]
let me merge the pr about fixing br i'll do extra checks like comparing code with vanilla br

**Comment by nadenislamarre** [comment]
to confirm prs. but this pr seems good to me.

**Comment by nadenislamarre** [comment]
conflicts

**Comment by liberodark** [comment]
Conflict fixed

**Comment by nadenislamarre** [comment]
pipewire is not broken on my side
do we really need this pr ?

**Comment by liberodark** [comment]
Is not broken on my side too with last fixes.
Im think better to wait for this pr.
If you have issue merge this.

**Pull request closed without merging**
