### PR TITLE
bump ffmpeg

### PR DESCRIPTION
**Pull request by mistepien**

### CODE REVIEW

**Comment by tcamargo** [comment]
Why?

**Comment by mistepien** [comment]
https://git.ffmpeg.org/gitweb/ffmpeg.git/shortlog/n4.2.2

this is not a completely new version but 4.2.1 with huge number of fixes.

**Comment by nadenislamarre** [comment]
i suggest we do first a br bump + this kind of bumps after 5.26 ?
bump ffmpeg is always a pain while it is used in emulators like ppsspp, in kodi, in splash, and each of them is compatible with one or an other version. some of them use a specific version of ffmpeg compiled for them, so, not sure it is the right moment.
personnally, i would prefer we start to go on 5.26 (stabilize the current master).
We can keep that pr for just after if br merge doesn't already include it.

**Comment by tcamargo** [comment]
Same here. Unless there is a clear improvement/correction, I would hold on that update.

**Comment by mistepien** [comment]
Ok I got it. This is clear policy I was not aware of.

**Pull request closed without merging**
