### PR TITLE
enable PIC when compiling libfreeimage on aarch64 for x86_64

### PR DESCRIPTION
**Pull request by bryanforbes**
If `-fPIC` is not added, the compiler complains with:

```
/x86_64/host/lib/gcc/x86_64-buildroot-linux-gnu/13.3.0/../../../../x86_64-buildroot-linux-gnu/bin/ld: ./Source/FreeImage/BitmapAccess.o: relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
```

### CODE REVIEW

**Comment by Ntemis** [comment]
We don't build on aarch64 but this change doesn't break anything, so is a GTG from my view even if personally cannot verify the change to be valid.

**Comment by bryanforbes** [comment]
> We don't build on aarch64

I'm submitting changes to enable building batocera on Apple Silicon using Docker so I more people (like myself) can help with the project

**Comment by udance4ever** [comment]
I verified this fix works targeting `bcm2836` while on an M1 Mac.

the `#ifeq` statements could be more generalized - I had to take both of them out for it to work (and happy it does!) as I'm building in Ubuntu arm64 VM (macOS VMWare) or container (Asahi Linux Docker)

also notice an else clause appears to be missing to preserve `TARGET_CXX_FLAGS` (and keep `LIBFREEIMAGE_CXXFLAGS` from going undefined)

great patch.

**Comment by bryanforbes** [comment]
> the `#ifeq` statements could be more generalized - I had to take both of them out for it to work (and happy it does!) as I'm building in Ubuntu arm64 VM (macOS VMWare) or container (Asahi Linux Docker)

Yeah, I was trying to be as conservative as possible, so I only enabled the flag when you're compiling for `x86_64` on `aarch64`, and compiling for `bcm2836` on an M1 Mac only meets one of the criteria. I wonder if it needs to be enabled any time someone is compiling on `aarch64` no matter what.

> also notice an else clause appears to be missing to preserve `TARGET_CXX_FLAGS` (and keep `LIBFREEIMAGE_CXXFLAGS` from going undefined)

Good catch. I should probably set `LIBFREEIMAGE_CXXFLAGS=$(TARGET_CXXFLAGS)` before doing the `ifeq` statements.

**Comment by dmanlfc** [comment]
a couple of observations to tidy the `#batocera` changes...

```
ifeq ($(BR2_ARM_CPU_HAS_NEON)$(BR2_ARM_FPU_FP_ARMV8)$(BR2_ARM_CPU_ARMV8A),y)
	LIBFREEIMAGE_CFLAGS += $(TARGET_CFLAGS) -DPNG_ARM_NEON_OPT=0
else
	LIBFREEIMAGE_CFLAGS += $(TARGET_CFLAGS)
endif
```

and then like so...

```
ifeq ($(HOSTARCH),aarch64)
ifeq ($(BR2_x86_64),y)
	LIBFREEIMAGE_CFLAGS += -fPIC -std=c++11
else
	LIBFREEIMAGE_CFLAGS += -std=c++11
endif
else
	LIBFREEIMAGE_CFLAGS += -std=c++11
endif

define LIBFREEIMAGE_BUILD_CMDS
	$(TARGET_MAKE_ENV) $(TARGET_CONFIGURE_OPTS) \
		CFLAGS="$(LIBFREEIMAGE_CFLAGS)" \
		CXXFLAGS="$(LIBFREEIMAGE_CFLAGS)" \
		$(MAKE) -C $(@D)
endef
```

**Comment by bryanforbes** [comment]
I've made updates to address the issues that were pointed out. @dmanlfc I took a slightly different approach to the second block than you suggested.

**Comment by udance4ever** [comment]
> I wonder if it needs to be enabled any time someone is compiling on aarch64 no matter what.

I actually think this is true.  Given compiling on `aarch64` is more of the exception than the norm, at the moment, perhaps take the x86_64 conditional out and we’ll sort this out as as try to cross-compile other boards over time?

**Pull request merged**
