### PR TITLE
bump default kernel version to 5.4.32

### PR DESCRIPTION
**Pull request by mistepien**

### CODE REVIEW

**Comment by tcamargo** [comment]
why would you like to get a newer kernel?

**Comment by mistepien** [comment]
There is a fix related to drm/i915

Excerpt from kernel changelog:
    drm/i915: Fix ref->mutex deadlock in i915_active_wait()
    
    The following deadlock exists in i915_active_wait() due to a double lock
    on ref->mutex (call chain listed in order from top to bottom):
     i915_active_wait();
     mutex_lock_interruptible(&ref->mutex); <-- ref->mutex first acquired
     i915_active_request_retire();
     node_retire();
     active_retire();
     mutex_lock_nested(&ref->mutex, SINGLE_DEPTH_NESTING); <-- DEADLOCK
    
    Fix the deadlock by skipping the second ref->mutex lock when
    active_retire() is called through i915_active_request_retire().
    
    Note that this bug only affects 5.4 and has since been fixed in 5.5.
    Normally, a backport of the fix from 5.5 would be in order, but the
    patch set that fixes this deadlock involves massive changes that are
    neither feasible nor desirable for backporting [1][2][3]. Therefore,
    this small patch was made to address the deadlock specifically for 5.4.


there is also fix:
- drm/amdgpu: correct ROM_INDEX/DATA offset for VEGA20
- drm/amd/display: fix dcc swath size calculations on dcn1

**Comment by tcamargo** [comment]
@nadenislamarre fine for you?
@mistepien did you get a working image with that new kernel?

**Comment by nadenislamarre** [comment]
the change number is low. i guess it is ok.

@mistepien generally, we update kernel by upgrading br, but sometimes, when there are issues it is ok to do like this.
can you first confirm it fixes your bug ? (i mean, did you compile and test ?)

**Comment by mistepien** [comment]
I got it with 5.4.31. It works just fine with my x86_64. I need two days to recompile whole system with 5.4.32.

Actually I didn't suffer a bug, but potentially someone may taking into account that amd gpu and intel gpu are quite popular. After all we deal here with LTS kernel version so what we face are almost exclusively bugfixes.

**Comment by nadenislamarre** [comment]
@mistepien you don't need to recompile all the system when updating the kernel even if it's cleaner. Don't hesitate to ask me on the chat for tips to compile/work faster.
for a linux kernel, i would regenerate in delta by "make", and for others packages, in case you've not read, i strongly use rsync : https://wiki.batocera.org/doku.php?id=batocera.linux_buildroot_modifications

**Pull request merged**
